# Exception

여러분의 Dart 코드는 예외를 던지고 받을 수 있습니다. 예외는 의도치 않은 일이 발생한 것을 나타내는 에러입니다. 만약 예외가 잡히지 않는다면, 예외를 발생한 isolate가 중지되고 일반적으로는 isolate 와 프로그램이 중지됩니다.

자바와는 다르게, 모든 Dart의 예외는 검사되지 않은 예외입니다. 메소드들은 발생할 수 있는 예외를 정의하지 않으며, 메소드들은 어떠한 예외도 받을 필요도 없습니다.

Dart는 Exception과 Error 와 미리 정의된 하위 타입들을 제공합니다. 당연히, 사용자 정의 예외도 만들 수 있습니다. 반면, Dart 프로그램들은 Exception과 Error 객체가 아닌 non-Null 객체를 예외로 던질 수 있습니다. 

## Throw

다음은, 예외를 던지는 예제입니다.

```dart
throw FormatException('Expected at least 1 section');
```

또한 임의의 객체를 던질 수 있습니다.

```dart
throw 'Out of llamas!';
```

> 노트: 제품 퀄리티의 코드는 일반적으로 Error와 Exception을 구현한 타입을 던집니다.

예외를 던지는 것은 표현이기 때문에, =>문 뿐만 아니라 표현을 허용하는 모든 곳에서 예외를 던질 수 있습니다.

```dart
void distanceto(Point other) => throw UnimplementedError();
```

## Catch

예외를 받게 되면, 발생한 예외를 멈춥니다. 예외를 받는 것은 이것을 처리할 기회를 주게 됩니다.

```dart
try{
    breedMoreLlamas();
} on OutOfLlamasException{
    buyMoreLlamas();
}
```

하나 이상의 타입의 예외를 던지는 코드를 처리하기 위해서는 복수의 catch 절을 정의해야 합니다. 던져진 객체의 타입에 맞는 첫 번째 catch 절은 예외를 처리합니다. 만약 catch 절이 타입을 명시하지 않는다면, 그 절은 모든 타입의 던져진 객체를 처리합니다.

 ```dart
 try{
     breedMoreLlamas();
 } on OutOfLlamasException{
     //특정한 예외
     buyMoreLlamas();
 } on Exception catch(e){
     //나머지 예외들
     print('Unknown exception $e');
 } catch(e){
     //정해진 타입 없이 모든 것 처리
     print('Something really unknown $e');
 }
 ```
 위의 코드를 보듯이, `on`과 `catch` 둘 다 쓸 수 있습니다. 특정한 예외 타입을 지정할 때에 `on`을 사용하세요. 예외 핸들러에서 예외 객체가 필요한 경우 `catch`를 사용하세요.

`catch()`에 하나 혹은 두개의 인자를 정의할 수 있습니다. 첫 인자는 던져진 예외이고, 두번째는 stack trace입니다.
```dart
try{
    ...
} on Exception catch(e){
    print('Exception details:\n $e');
} catch(e, s){
    print('Exception details:\n $e');
    print('Stack trace:\n $s');
}
```
부분적으로 예외를 처리하고 전파를 위해서는 `rethrow`키워드를 사용하세요